### ISSUE TITLE
Extracting Exif Data

### ISSUE THREAD

**Issue by awestbro** [akash-akya/vix#100]
I'm having trouble extracting exif image data from the "UserComment" field from the following image:

![00000-4105013426](https://user-images.githubusercontent.com/3393293/229839123-b8b7228d-c1e0-4843-80fd-764a2832abf1.jpeg)

My code for extracting the UserComment field looks like:

```elixir
headers = Vix.Vips.Image.header_field_names(image)
IO.inspect(headers)
header_string = Vix.Vips.Image.header_value_as_string(image, "exif-ifd2-UserComment")
header_value = Vix.Vips.Image.header_value(image, "exif-ifd2-UserComment")
IO.inspect({header_string, header_value})
```

Output:

```
{:ok,
 ["exif-ifd2-ColorSpace", "exif-ifd2-FlashpixVersion", "exif-ifd2-ExifVersion",
  "exif-ifd2-UserComment", "exif-ifd0-ResolutionUnit", "exif-ifd0-YResolution",
  "exif-ifd0-XResolution", "exif-data", "jpeg-chroma-subsample",
  "jpeg-multiscan", "vips-sequential", "vips-loader", "filename", "yres",
  "xres", "yoffset", "xoffset", "interpretation", "coding", "format", "bands",
  "height", "width"]}
{{:ok,
  "Unsupported UNICODE string (Unsupported UNICODE string, Undefined, 400 components, 400 bytes)"},
 {:ok,
  "Unsupported UNICODE string (Unsupported UNICODE string, Undefined, 400 components, 400 bytes)"}}
```

The UserComment field from properties should be:  "Character concept design, hd Steps: 22, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 4105013426, Face restoration: CodeFormer, Size: 400x600, Model hash: e6415c4892, Model: realisticVisionV20_v20"

I think this should return an {:error, _} tuple in this case. Any suggestions?

**Comment by awestbro** [comment]
Here is what it metadata2go gives me for this file:

![image](https://user-images.githubusercontent.com/3393293/229841242-a809f72b-5658-4935-9dd3-3147df8cf6ab.png)

**Comment by akash-akya** [comment]
Hi @awestbro, this looks like an issue related to the string encoding (UCS-2) which is not well-supported. If my understanding is correct, that part of the spec is not very clear on interpreting the data. Some details about the encoding issue here: https://github.com/SixLabors/ImageSharp/issues/1919

This is coming from the library (libexif) we are using to read exif data, so unfortunately there is no solution for this as of now.

I opened an issue there: https://github.com/libexif/libexif/issues/101
