### ISSUE TITLE
Return type of Vix.Vips.Image.format/1 incorrect

### ISSUE THREAD

**Issue by kipcole9** [akash-akya/vix#101]
Currently the `@spec` for `Vix.Vips.Image.format/1`  is:
```elixir
@spec format(t()) :: term() | no_return()
```
Based upon the [libvips docs](https://libvips.github.io/libvips/API/current/libvips-header.html#vips-image-get-format) I believe the spec should be:
```elixir
@spec format(t()) :: Vix.Vips.Operation.vips_band_format() | no_return()
```

**Comment by akash-akya** [comment]
Thanks for reporting! fixed now
