### ISSUE TITLE
Precompiled download fails on OTP26

### ISSUE THREAD

**Issue by simonprev** [akash-akya/vix#117]
When upgrading to OTP 26, the following crash happens when attempting to download the binary:

<img width="1225" alt="image" src="https://github.com/akash-akya/vix/assets/464900/16a199b1-674a-4c48-9adb-43a71db1038a">

Seems to be related to `httpc`

**Comment by akash-akya** [comment]
Hi @simonprev, thanks for catching the issue.

I fixed and released a new version, can you test `v0.22.0`? 

There is also httpc version, but you that only happen if it fails to find precompiled binaries. 
I'll fix that issue separately

**Comment by kevincote** [comment]
Hi @akash-akya, I can confirm that it works with `v0.22.0`. Thanks for the quick fix !
