### ISSUE TITLE
How do you bring your own libvips?

### ISSUE THREAD

**Issue by axelson** [akash-akya/vix#122]
In the readme it states that you can bring your own libvips by installing it manually and ask vix to use that instead, but I'm not able to figure out how to do so from the rest of the readme and docs. I can see how to compile vips as part of the elixir compilation but I can't figure out how to use a vips that I've compiled myself.

**Comment by akash-akya** [comment]
Hi @axelson,

You can do that by setting `VIX_COMPILATION_MODE` system env variable to `PLATFORM_PROVIDED_LIBVIPS`. During the compilation and runtime. like `export VIX_COMPILATION_MODE="PLATFORM_PROVIDED_LIBVIPS"`

When you set this env variable,  vix tries to fetch required libraries and headers using `pkg-config`, then compiles NIF libraries using those.

Some details here: https://github.com/akash-akya/vix#pre-compiled-nif-and-libvips

Let me know if you are facing any issues or if the details are not clear.

**Comment by akash-akya** [comment]
Hi @axelson, let me know if you are still facing the issue. Or if you have suggestions to improve the documentation.
Meanwhile, I am closing this :)
