### ISSUE TITLE
image href svg render

### ISSUE THREAD

**Issue by Leastrio** [akash-akya/vix#125]
Is there a way to render image tags with url hrefs? Using `Vix.Vips.Operation.svgload_buffer!` doesnt like them and just doesnt fetch the image and embed it.

**Comment by akash-akya** [comment]
Hey @Leastrio, are you trying to fetch the image over the network? afaik rsvg, the library libvips uses to render svg, only supports `data://` or `file://` schema. If possible, can you share a sample code which is failing

**Comment by Leastrio** [comment]
Ah okay that would make sense. I guess a workaround would be to just fetch the image myself and insert it into the svg data.
