### ISSUE TITLE
New empty image

### ISSUE THREAD

**Issue by leonardorame** [akash-akya/vix#127]
Hi, I need to create an empty image, with a predefined width and height, and a background color. Like a canvas for placing other images above it. How can I do that.

Regards,
Leonardo.

**Comment by leonardorame** [comment]
I found with `Operation.black `I can create a new black image:

`black = Operation.black!(100, 100)`

This is ok, now, how can I create a new white (or other color) image?.

**Comment by akash-akya** [comment]
Hey @leonardorame, there are multiple ways to achieve what you want, if you want just white colour then you can just invert black image you just created using `Operation.invert!(black)` operation.

If you want different colour you can use `Operation.linear!(image, [1], [r, g, b])` operation. 

Btw `black!` by default creates image with single band, but if you are working with colour you need 3 bands, so use `Operation.black!(100, 100, bands: 3)`

**Comment by leonardorame** [comment]
Hi @akash-akya, thank you for the hint. 

Now in `Operation.linear!(image, [1], [r, g, b]),` you pass an image parameter, how can I create an instance of it?

**Comment by akash-akya** [comment]
You can pass the image you created using `black!` operation. 

Example:
```
black = Operation.black!(100, 100, bands: 3)
red_img = Operation.linear!(black, [1], [255, 0, 0])
```

**Comment by leonardorame** [comment]
Great!!!, thank you.
