### ISSUE TITLE
Joining a B/W image over an RGB background

### ISSUE THREAD

**Issue by leonardorame** [akash-akya/vix#128]
Hi, I created a colour background thanks to the help of @akash-akya  by using this:

```
img = Operation.black!(1000, 800, bands: 3)
red_img = Operation.linear!(img, [1], [100, 0, 0])
```

Now I want to insert an image over that red background, but for some reason I cannot insert, by using this code:

`{:ok, joined_img} = Operation.insert(red_img, img, 20, 20)`

The result is this:

![imagen](https://github.com/akash-akya/vix/assets/1405017/94fc0ea4-94a5-4d8a-8080-563e68e04d92)

**Comment by leonardorame** [comment]
If I change the background to 1 band this way:

black = Operation.black!(1000, 800, bands: 1)
red_img = Operation.linear!(black, [1], [100])

I get this (the image is shown correctly):

![imagen](https://github.com/akash-akya/vix/assets/1405017/d35c4035-a07d-400f-872d-ca84450d258a)

It looks like the original image is in grayscale. How can I insert it into a colour background?

**Comment by akash-akya** [comment]
@leonardorame, You need to match the color space. I am guessing the image is single band but background you are creating is a 3 band image.

There are a multiple way to achieve what you what but if you just want to add background to the image you can do something like this:

```elixir
alias Vix.Vips.{Image, Operation}

bw_img
|> Operation.colourspace!(:VIPS_INTERPRETATION_sRGB) # convert colourspace from B_W to sRGB
|> Operation.embed!(10, 10, Image.width(bw_img) + 20, Image.height(bw_img) + 20,
  extend: :VIPS_EXTEND_BACKGROUND,
  background: [100, 0, 0]  #  red color background 
)
```

The important bit is `Operation.colourspace!(image, :VIPS_INTERPRETATION_sRGB)`
