### ISSUE TITLE
Segfault on long operations chain of Vix.Vips.Operation.rank/4.

### ISSUE THREAD

**Issue by kipcole9** [akash-akya/vix#144]
Opening an issue here to reflect https://github.com/elixir-image/image/issues/125.

A repeatable test case (at least on my M1 Max MacBook Pro 64Gb) is:
```elixir
# The test image
{:ok, {_code, _headers, data}} = :httpc.request('https://raw.githubusercontent.com/elixir-image/image/main/test/support/images/tulips.png')
tulips = :erlang.list_to_binary(data)
{:ok, image} = Vix.Vips.Image.new_from_buffer(tulips)
mask = Vix.Vips.Operation.invert!(image[-1])
dilated = Enum.reduce(1..500, mask, fn _i, acc -> Vix.Vips.Operation.rank!(acc, 3, 3, 8) end)
Vix.Vips.Image.write_to_binary(dilated)
```
You should be able to just copy/paste the script above and I expect you will see a segfault a the `write_to_binary/1` call.

CC: @ramyma

**Comment by akash-akya** [comment]
Hey @kipcole9. Thanks for creating the small case to test.
I'll check and get back to you.

**Comment by akash-akya** [comment]
Looks like upstream issue https://github.com/libvips/libvips/issues/3832. Waiting for the confirmation.
