### ISSUE TITLE
Warning on Elixir 1.16

### ISSUE THREAD

**Issue by thbar** [akash-akya/vix#147]
While upgrading our app, I met:

```
==> vix
Compiling 27 files (.ex)
     warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
     │
 494 │                 Logger.warn("argument must be stream of iodata")
     │                        ~
     │
     └─ lib/vix/vips/image.ex:494:24: Vix.Vips.Image.new_from_enum/2

Generated vix app
```

Inocuous but I thought I would report it here!

**Comment by akash-akya** [comment]
Hi @thbar, this is fixed [recently](https://github.com/akash-akya/vix/pull/146) with version [`v0.27.0`](https://diff.hex.pm/diff/vix/0.26.0..0.27.0). Can you check if you are using latest version?
