### ISSUE TITLE
How to load a specific page from image

### ISSUE THREAD

**Issue by moski** [akash-akya/vix#168]
We have an ICO image, with 4 different page. We can't find any option to load a specific page. I can see from the C binding that

```
ERL_NIF_TERM nif_image_new_from_file(ErlNifEnv *env, int argc,
                                     const ERL_NIF_TERM argv[])
```

Takes arguments, but there is no way to pass page into new_from_file.

For example, in the Ruby version, you can do:

```
Vips::Image.new_from_file(@path, page: page)
```

Sample image: https://149426355.v2.pressablecdn.com/wp-content/themes/sixcolors/images/favicon.ico

**Comment by akash-akya** [comment]
Hi @moski, you can pass loader option as a suffix to the path:

```elixir
{:ok, img} = Vix.Vips.Image.new_from_file("~/Downloads/favicon.ico[page=3]")
```

I'll add support for additional keyword list argument too

**Comment by moski** [comment]
Like magic, works 100%. 

Thank you for the fast reply and thank you for the amazing library. I've also noticed, that ico format doesn't work with PRECOMPILED_NIF_AND_LIBVIPS. I had to use `VIX_COMPILATION_MODE=PLATFORM_PROVIDED_LIBVIPS` 

Maybe it's worth to add it to the docs as well.

**Comment by akash-akya** [comment]
Thanks.

Yeah, precompiled libvips only supports few formats. Formats are mentioned [here](https://github.com/akash-akya/vix?tab=readme-ov-file#pre-compiled-nif-and-libvips), but I guess it is not easy to spot with all other details
