### ISSUE TITLE
`:invalid_path` on v0.31.0

### ISSUE THREAD

**Issue by leandrocp** [akash-akya/vix#173]
Calling [Image.open/2](https://hexdocs.pm/image/Image.html#open/2) with `{:vix, "0.31.0"}` started returning `{:error, :invalid_path}` for any image I try to open (tested with 2 png files). Downgrading to `{:vix, "0.30.0"}` works fine.

```
iex> Image.open("beacon.png")
{:error, :invalid_path}
```

```
❯ elixir -v
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.17.2 (compiled with Erlang/OTP 27)
```

/edit please let me know If I can help with something or what other information I can give to help. Thanks!

**Comment by akash-akya** [comment]
@leandrocp fixed the issue in the latest release https://hex.pm/packages/vix/0.31.1. 
Thanks for the reporting!

**Comment by leandrocp** [comment]
@akash-akya can confirm it's working now. Thanks for the quick fix!
