### ISSUE TITLE
Process stucks when using Image.new_from_enum

### ISSUE THREAD

**Issue by a3mar** [akash-akya/vix#179]
Greetings! I've found strange behavior with Image.new_from_enum method. When you pass incorrect arguments like this:
```elixir
iex(1)> alias Vix.Vips.Image, as: Img
Vix.Vips.Image
iex(2)> Img.new_from_enum 1..100

21:29:31.420 [warning] argument must be stream of iodata
```
or
```elixir
iex(1)> alias Vix.Vips.Image, as: Img
Vix.Vips.Image
iex(2)> Img.new_from_enum []
```
process blocks and waiting for something. Same situation reproduces (not every time) with broken pictures with incorrect encoding.

I found very strange workaround, if at first i call this method with arg like [<<128>>], it returns error, and after this error it working correctly:
```elixir
iex(1)> alias Vix.Vips.Image, as: Img
Vix.Vips.Image

iex(2)> Img.new_from_enum [<<128>>]
{:error, "Failed to create image from VipsSource"}

iex(3)> Img.new_from_enum []
{:error, "Failed to create image from VipsSource"}

iex(4)> Img.new_from_enum 1..100

21:40:50.912 [warning] argument must be stream of iodata
{:error, "Failed to create image from VipsSource"}

```

**Comment by akash-akya** [comment]
Hi @a3mar, I tried several times and I am not able to reproduce this. Can try this with latest Vix? are you using prebuilt libvips (default) or you are using custom/platform-provided libvips?

**Comment by a3mar** [comment]
Hmm. I tired  to reproduce with blank project with same deps, and all is ok. Also, i tried to delete _build and deps folders from my project, download and compile all from scratch, and problem reproduces 10/10 times. Even if i removed all children from supervisors. 

Then, sorry, it looks like problem with my project. If you have advice how to debug this - i'll be grateful.

I'm using bundled libvips, latest vix  0.31.1, elixir 17.3, Erlang/OTP 27 [erts-15.1.2] and have some deps in project:
```elixir
defp deps do
    [
      {:credo, "~> 1.7", only: [:dev, :test], runtime: false},
      {:plug_cowboy, "~> 2.0"},
      {:vix, "~> 0.31.1"},
      {:castore, "~> 1.0"},
      {:mint, "~> 1.0"},
      {:jason, "~> 1.4"},
      {:ex_json_schema, "~> 0.10.2"},
      {:prom_ex, "~> 1.11.0"}
    ]
  end
```

**Comment by akash-akya** [comment]
@a3mar check if you have `.iex.exs` in the repo? If yes then maybe it is affecting it?

**Comment by a3mar** [comment]
Thank you, its solved, i removed mix.lock, rebuild deps and now problem not exist. Sorry for disturbing, my fail
