### ISSUE TITLE
mix compile failed

### ISSUE THREAD

**Issue by krushi123** [akash-akya/vix#18]
I am adding this on to a Phoenix project.  Phoenix version 1.6.2
I am getting an error ```Package vips was not found in the pkg-config search path.```
Verified that libvips, pkg-config, gcc are installed. 
installed erlang-dev package also.
I am working on wsl on Windows 11. 
Any suggestions?

**Comment by akash-akya** [comment]
Can you confirm you installed `libvips-dev` too? pc file required by pkg-config will be that package I think

**Comment by krushi123** [comment]
Thanks a ton @akash-akya ! Installing ```libvips-dev``` solved the compilation issue.

**Comment by akash-akya** [comment]
Nice! I'll mention this in the readme too
