### ISSUE TITLE
getting image metadata

### ISSUE THREAD

**Issue by ringofhealth** [akash-akya/vix#2]
Hi! 

Awesome library!! Super fast and really easy to use.

I have a quick question, I been looking through the documentation, there doesnt seem to be a way to fetch image width/height. Maybe I am missing something, but I was looking for something like this

https://hexdocs.pm/elxvips/Elxvips.html#get_image_sizes/1

but obv your lib is much more extensive and support more operations. Could you point me to the right direction to how to get a image max height/width and other meta information?

**Comment by akash-akya** [comment]
Hi,

Thanks for your kind words :)

Image metadata is not available yet, I overlooked it I guess. I will try to add it soon.

**Comment by akash-akya** [comment]
Added support for image headers. Please check `v0.2.0`
