### ISSUE TITLE
How to pass optional arguments?

### ISSUE THREAD

**Issue by krushi123** [akash-akya/vix#21]
```elixir
# create image thumbnail.
# this function accepts many optional parameters, see: https://libvips.github.io/libvips/API/current/Using-vipsthumbnail.md.html
# also see `Operation.thumbnail/3` which accepts image path
{:ok, thumb} = Operation.thumbnail_image(img, 100)
```
How to pass the optional arguments to the function? as atom? as Map?
For example, there is ```--smartcrop``` option is available for the function. How do you pass this option to Operation.thumbnail_image(img, 100) function?

**Comment by akash-akya** [comment]
Hi @krushi123,

You can check [spec](https://hexdocs.pm/vix/Vix.Vips.Operation.html#thumbnail_image/3). `thumbnail_image` takes keyword list as third argument, and this argument is optional. It's an empty list by default.

For smart crop it would be something like this 
```elixir
{:ok, thumb} = Operation.thumbnail_image(img, 100, crop: :VIPS_INTERESTING_ATTENTION)
```

**Comment by krushi123** [comment]
Comprehensive.  Missed it. Thanks a lot.
