### ISSUE TITLE
Add `mapim` example?

### ISSUE THREAD

**Issue by GavinJoyce** [akash-akya/vix#22]
👋 Hi, I hope it's ok to ask this question here. Feel free to close if it isn't the right place.

I've been trying to replicate the following transforms with `mapin` without much success so far:

 * http://libvips.blogspot.com/2015/11/fancy-transforms.html
 * https://stackoverflow.com/a/50219715

Both the Python and Ruby libraries in the examples below allow operations on the index image like this:

```python
centre = index - [image.width / 2, image.height / 2]
```

Is there an equivalent way of doing these types of operations with `vix`?

Also, if I can figure out how to replicate some of these transforms with `vix`, would you be interested in an example in the readme? I'd be happy to submit a PR.

**Comment by GavinJoyce** [comment]
I've made some progress on the [first python example](http://libvips.blogspot.com/2015/11/fancy-transforms.html), I came across [`Operation.wrap`](https://hexdocs.pm/vix/Vix.Vips.Operation.html#wrap/2) which takes care of `centre = index - [image.width / 2, image.height / 2]`. I'll try figure out the rest tomorrow

```elixir
def wobble(image) do
    # this makes an image where pixel (0, 0) (at the top-left) has value [0, 0],
    # and pixel (image.width, image.height) at the bottom-right has value
    # [image.width, image.height]
    width = Image.width(image)
    height = Image.height(image)
    {:ok, index} = Operation.xyz(width, height)
    
    # make a version with (0, 0) at the centre, negative values up and left,
    # positive down and right
    index = Operation.wrap!(index, x: Integer.floor_div(width, 2), y: Integer.floor_div(height, 2))

    # to polar space, so each pixel is now distance and angle in degrees
    # TODO: convert to elixir:
    # polar = centre.polar()

    # scale sin(distance) by 1/distance to make a wavey pattern
    # TODO: convert to elixir:
    # d = 10000 * (polar[0] * 3).sin() / (1 + polar[0])

    # and back to rectangular coordinates again to make a set of vectors we can
    # apply to the original index image
    # TODO: convert to elixir:
    # index += d.ibandjoin(polar[1]).rect()

    # finally, use our modified index image to distort the input!
    Operation.mapim(image, index)
end
```

**Input**

![keane](https://user-images.githubusercontent.com/2526/147648181-056b4fe7-15aa-4ec7-8bce-65db8d45eabe.jpeg)

**Output**

![keane-out](https://user-images.githubusercontent.com/2526/147648200-5cefb259-1a6d-400c-a805-cb10d4908ec7.jpeg)

**Comment by GavinJoyce** [comment]
Making progress. These seem to be the equivalent:

Python
```python
polar = centre.polar()
```

Elixir
```elixir
polar = Operation.complex!(center, :VIPS_OPERATION_COMPLEX_POLAR)
```

---

I _think_ this is also close:

Python
```python
(polar[0] * 3).sin()
```

Elixir
```elixir
polar_band_0 = Operation.extract_band!(polar, 0)
polar_band_0_x_3 = Operation.linear!(polar_band_0, [3.0], [0.0])
polar_band_0_x_3_sin = Operation.math!(polar_band_0_x_3, :VIPS_OPERATION_MATH_SIN)
```

I get an error on the last statement however, `(Vix.Vips.Operation.Error) operation build: math: image must be non-complex`

**Comment by GavinJoyce** [comment]
^ looks similar to https://github.com/libvips/php-vips/issues/81

**Comment by GavinJoyce** [comment]
I tried to recreate jcupitt's example in https://github.com/libvips/php-vips/issues/81#issuecomment-449563805:

```elixir
def wobble(image) do
    # this makes an image where pixel (0, 0) (at the top-left) has value [0, 0],
    # and pixel (image.width, image.height) at the bottom-right has value
    # [image.width, image.height]
    width = Image.width(image)
    height = Image.height(image)

    index = Operation.xyz!(width, height)

    # make a version with (0, 0) at the centre, negative values up and left,
    # positive down and right
    center = Operation.wrap!(index, x: Integer.floor_div(width, 2), y: Integer.floor_div(height, 2))

    # turn into a complex image, then go to polar coordinates
    # $polar = $centre->copy(['format' => 'complex', 'bands' => 1])->polar();
    polar = center
    |> Operation.copy!(format: :VIPS_FORMAT_COMPLEX, bands: 1)
    |> Operation.complex!(:VIPS_OPERATION_COMPLEX_POLAR)

    # get the real (distance) part and scale sin(distance) by 1/distance to
    # make a wavey pattern
    # $d = $polar->real();
    # $sd = $d->multiply(3)->sin()->multiply(10000)->divide($d->add(1));

    d = Operation.complexget!(polar, :VIPS_OPERATION_COMPLEXGET_REAL)
    sd = d
    |> Operation.linear!([3.0], [0.0])
    |> Operation.math!(:VIPS_OPERATION_MATH_SIN)
    |> Operation.linear!([10000.0], [0.0])
    |> Operation.divide!(Operation.linear!(d, [1.0], [1.0]))

    # and back to rectangular coordinates again to make a set of vectors we can
    # apply to the original index image
    # $rect = $sd->complexform($polar->imag())->rect();

    rect = sd
    |> Operation.complexform!(Operation.complexget!(polar, :VIPS_OPERATION_COMPLEXGET_IMAG))
    |> Operation.complex!(:VIPS_OPERATION_COMPLEX_RECT)

    # out of complex space
    rect = Operation.copy!(rect, format: :VIPS_FORMAT_FLOAT, bands: 2)
    index = Operation.add!(index, rect)

    # finally, use our modified index image to distort the input!
    Operation.mapim(image, index)
end
```

I must have made a mistake somewhere however as the output image is the same as the input

**Comment by akash-akya** [comment]
Hi @GavinJoyce, sorry for the delayed response. I was having health issues and was away from keyboard.

Thank you for detailed issue description and updating your progress.

Vix does not have operators like `-`, `/` yet, you have to use respective operations like `subtract` & `divide` etc.

For `centre = index - [image.width / 2, image.height / 2]` you can simply use [`linear`](https://hexdocs.pm/vix/Vix.Vips.Operation.html#linear/4) operation. Like 

```elixir
[half_width, half_height] = [Integer.floor_div(width, 2), Integer.floor_div(height, 2)]
center = Operation.linear!(index, [1, 1], [-half_width, -half_height])
```

For the wobble example you shared, I got this output with the following change

```diff
  # make a version with (0, 0) at the centre, negative values up and left,
  # positive down and right
-  center = Operation.wrap!(index, x: Integer.floor_div(width, 2), y: Integer.floor_div(height, 2))
+ [half_width, half_height] = [Integer.floor_div(width, 2), Integer.floor_div(height, 2)]
+ center = Operation.linear!(index, [1, 1], [-half_width, -half_height])
```

![index](https://user-images.githubusercontent.com/9396022/148208016-8d04f06e-d74f-4612-8b48-7b460a22a4d5.png)

I'll try to update readme to make this more clear.

**Comment by GavinJoyce** [comment]
That's perfect @akash-akya, thank you!
