### ISSUE TITLE
Does `mapim` support `interpolate` option?

### ISSUE THREAD

**Issue by GavinJoyce** [akash-akya/vix#23]
Looking at the `Vix` API, it seems that `mapim` might not support the `interpolate` option that's available in the libvips API. Is that correct?

https://hexdocs.pm/vix/Vix.Vips.Operation.html#mapim/3 
https://www.libvips.org/API/current/libvips-resample.html#vips-mapim

<img width="927" alt="Screenshot 2021-12-29 at 17 38 03" src="https://user-images.githubusercontent.com/2526/147689254-53494cbb-5ea8-4300-9d3d-2fe680793519.png">

If I can figure out how to add support for the `interpolate` option, would you be open to the PR?

**Comment by akash-akya** [comment]
@GavinJoyce I went ahead and added support for vips-interpolate. If possible, can you try the latest master?

```elixir
{:vix, git: "https://github.com/akash-akya/vix.git"}
```

Example usage

```elixir
alias Vix.Vips.Operation
alias Vix.Vips.Interpolate

Operation.mapim(image, index, interpolate: Interpolate.new!("bilinear"))
```

**Comment by GavinJoyce** [comment]
@akash-akya thanks for adding support for interpolate!

I tested master and it seems to work great. Here are some example outputs:

**nearest**

`Operation.mapim(image, index, interpolate: Interpolate.new!("nearest"))`

![output-wobble-nearest](https://user-images.githubusercontent.com/2526/148366128-3501c768-0910-48c6-93b0-c8a7bc5d5598.png)

**bilinear**

`Operation.mapim(image, index, interpolate: Interpolate.new!("bilinear"))`

![output-wobble-bilinear](https://user-images.githubusercontent.com/2526/148366198-7c9b86a4-502f-4e2e-8b8f-6fdb30dff6e1.png)

**vsqbs**

`Operation.mapim(image, index, interpolate: Interpolate.new!("vsqbs"))`

![output-wobble-vsqbs](https://user-images.githubusercontent.com/2526/148366316-7d86e3e1-84bc-4b57-a805-363e6a5fc972.png)
