### ISSUE TITLE
Does vix support creating GIFs?

### ISSUE THREAD

**Issue by GavinJoyce** [akash-akya/vix#25]
I think the answer is likely no, just want to make sure before I shell out to python or ruby (which I'm fine with). I also understand that this library does not yet have complete API support.

With [`pyvips`](https://github.com/libvips/pyvips), I can create a GIF from a list of `frames` as follows:

```python
gif_image = pyvips.Image.arrayjoin(frames, across=1)
gif_image.set_type(pyvips.GValue.gint_type, "page-height", gif_height)
gif_image.set_type(pyvips.GValue.array_int_type, "delay", [100] * len(frames))
gif_image.write_to_file("output.gif", dither=0.5, effort=3, bitdepth=7)
```

I can also do the same with [`ruby-vips`](https://github.com/libvips/ruby-vips):

```ruby
gif_image = Vips::Image.arrayjoin(frames, across: 1)
gif_image = gif_image.mutate do |x|
    x.set_type! GObject::GINT_TYPE, "page-height", gif_height
    x.set_type! Vips::ARRAY_INT_TYPE, "delay", [100] * frames.length
end
gif_image.write_to_file("output.gif"), dither: 0.5, effort: 3, bitdepth: 7)
```

Looking at the [`vix` docs](https://hexdocs.pm/vix/Vix.Vips.Operation.html), I can't seem to find a way to change the `"page-height"` and `"delay"` metadata of the image.

Also, [`write_to_file/2`](https://hexdocs.pm/vix/Vix.Vips.Image.html#write_to_file/2) doesn't seem to support optional arguments like [`write_to_file`](https://libvips.github.io/ruby-vips/Vips/Image.html#write_to_file-instance_method) in `ruby-vips`

I'd usually ask if you'd accept a PR, however I'm not familiar with C and I'm pretty new to [`libvips`](https://www.libvips.org/) so I think a submitting a PR is beyond my current capabilities.

**Comment by akash-akya** [comment]
Vix does support creating gif.

```elixir
{:ok, frames} = Operation.arrayjoin(frames, across: 1)
:ok = Image.write_to_file(frames, "output.gif[page-height=450]")
```

And you can pass saver options as part of filename for now (`page-height` in the above example)

But setting image header `set_type!` is not supported yet.

**Comment by GavinJoyce** [comment]
Great, thanks for letting me know

**Comment by akash-akya** [comment]
Thanks for bringing this up, I'll create separate issue for tracking image mutations
