### ISSUE TITLE
Read from buffer?

### ISSUE THREAD

**Issue by cigrainger** [akash-akya/vix#29]
I've got a use case where I'd like to convert images in memory, acquired from an API. Is there a way to create a `Vix.Image.t()` from a buffer rather than just from file? Thanks! And thanks for the great package.

**Comment by akash-akya** [comment]
Hi @cigrainger.
I think you are after [`vips_image_new_from_buffer`](https://www.libvips.org/API/current/VipsImage.html#vips-image-new-from-buffer). Currently it's not supported, I'll try to add sometime this week

**Comment by akash-akya** [comment]
Hey @cigrainger, I pushed a new `Vix.Vips.Image.new_from_buffer/2` to [dev-img-from-buffer](https://github.com/akash-akya/vix/tree/dev-img-from-buffer) branch. If possible, can you try? This is a generic function which tries to recognize the format and use the corresponding loader.

If you already know the image format of the binary, you can use the corresponding `load_buffer` function from [`Vix.Vips.Operation`](https://hexdocs.pm/vix/Vix.Vips.Operation.html)

For example, for JPEG format,
```elixir
bin = File.read!("image.jpg")
{:ok, im} = Vix.Vips.Operation.jpegload_buffer(bin)

# use im for futher processing
```

**Comment by cigrainger** [comment]
Amazing! Thank you @akash-akya. I figured out that I could use `tiffload_buffer`! I'll try this out first thing tomorrow and report back.

**Comment by cigrainger** [comment]
Thanks @akash-akya. Works great!
