### ISSUE TITLE
Release vips connection?

### ISSUE THREAD

**Issue by kipcole9** [akash-akya/vix#34]
@akash-akya, This is such a good library and I'm back working on some higher level imaging APIs that lean very heavily on your work.

I was researching custom sources for libvips and found the [issue you opened](https://github.com/libvips/libvips/issues/1912) back in 2020 and then also see you have a development branch for this.

How close do you think this is to a releasable feature?  Custom source and target (with Elixir callbacks for read/write/seek?) would be awesome.

Thanks very much for the high quality work you do on this library.

**Comment by akash-akya** [comment]
Hi @kipcole9! 
Supporting custom source and sink would be awesome, but unfortunately calling Elixir/Erlang code from NIF is not possible without a lot of complicated coordination using Mutex and messaging, I wrote bit about this [here](https://elixirforum.com/t/calling-elixir-in-rust/40121/6). Although `vips-connection` branch sort-of works, I dont want to commit to this approach. So keeping it separate for now. I have a few more approaches in mind (still not as simple as I like it to be), but not finding time to test it out.

So, I'm not sure of merging `vips-connection` anytime soon 😅. I'll try to find time and test different approaches and see from there.

Also, It would be great if you can share a bit about your use-case. If we can have a simpler approach which covers the majority of use cases but not all, that would be great too.

And thanks for all your kind words. It means a lot :)

**Comment by kipcole9** [comment]
@akash-akya, I figured the challenges of having a NIF call out to BEAM code was a considerable challenge so I'm not surprised at your answer.

The use case for me is exactly the reason custom source and target were added to `libvips` - streaming. If there is a way to implement three scenarios then I think it will satisfy a large number use cases:

1. Being able to transform files from an HTTP URL in a streaming pipeline. So an image on S3 could be accessed as a custom source that is then transformed with `Vix` and then output to custom target (which might also be an HTTP sink).

2. Having a custom target that is `Enumerable` (in the Elixir protocol sense) would make a great abstraction for streaming images to a client connection in `Phoenix`. ie I would like to use [Plug.Conn.chunk/2](https://hexdocs.pm/plug/Plug.Conn.html#chunk/2) in a custom target

3. Last one is quite likely the simplest to implement. That is to have a file descriptor as a custom source and as a custom target. That way any Elixir code that reads and writes to a file could be used as a source and a target. I suspect use cases (1) and (2) above could be implemented on top of this. But I think they could both be more efficiently and resiliently implemented separately.

None of this is trivial I appreciate but it would be an incredibly valuable addition since streaming image transforms is a huge win in imaging pipelines.

**Comment by akash-akya** [comment]
@kipcole9 Thanks for sharing use cases, It is exactly same as the use cases I have in mind. 
And I agree to everything you said, supporting streaming is high-priority. I'll start experimenting with approach 3 and see from there.

**Comment by kipcole9** [comment]
That's super exciting to hear.  The recent changes to the [client hints for responsive images](https://wicg.github.io/responsive-image-client-hints/) draft specification involves re-writing EXIF headers to signal image dimensions and DPI.  A streaming VIPs client would make this a really fabulous solution (and this is the area I'm working on now).

**Comment by akash-akya** [comment]
Hi @kipcole9, I have an experimental branch for streaming support at https://github.com/akash-akya/vix/pull/36. 
If possible, can you take a look?

**Comment by kipcole9** [comment]
Wow, that's exciting. Will do this weekend and report back!  Thanks very much for working on this.

**Comment by kipcole9** [comment]
OK, have merged all the recent work into a local branch and will get familiar with the new streaming capability. Its am amazingly clean interface - really great work.

**Comment by kipcole9** [comment]
Closing in favour of the discuss on the PR
