### ISSUE TITLE
[Question] Matrix Operations

### ISSUE THREAD

**Issue by kipcole9** [akash-akya/vix#35]
One class of transforms requires matrix operations and access to pixel data. In the Python examples, the mutable nature of the language makes this straight forward, in Elixir of course not so simple.  Here's an example of what I'm looking to do (in Python):
```python
# turn to 8-bit unsigned so we can make a histogram
# use 0 - 255 to be -128 - +127 for a/b
# and 0 - 255 for 0 - 100 L
im += [0, 128, 128]
im *= [255.0 / 100, 1, 1]
im = im.cast("uchar")
```
This example happens to be mapping Lab values into a range so I can do a histogram and retrieve dominant colours in a perceptual space.

Any thoughts on the right approach for this kind of operation?

**Comment by kipcole9** [comment]
On further reading I think I've understood better the operation model.  To perform matrix operations like the python expressions above I believe the approach would be:
```elixir
add = Vix.Vips.Image.new_from_array([0, 128, 127])
img_sum = Vix.Vips.Operation.add(im, add)

mult = Vix.Vips.Image.new_from_array([255.0 / 100, 1, 1])
img_mult = Vix.Vips.Operation.multiply(img_sum, mult)
```
Does that sound about right?  It would require a new function `Vix.Vips.Image.new_from_array/1` that interfaces with `vips_image_new_matrix_from_array` if I've understood correctly.

**Comment by kipcole9** [comment]
And ... looks like `erl_list_to_vips_image_array` is the right call so `Vix.Vips.Image.new_from_array/1` could just be a NIF call to `erl_list_to_vips_image_array` for simple vectors?

**Comment by akash-akya** [comment]
That's correct @kipcole9. 

As you can see, there is a lot to improve in terms of ergonomics. I intentionally kept it open and only have raw operations closer to bindings at the moment.

Thanks for brining this up. We should get rid of intermediate operation to create `VipsImage`: 

```elixir
img_sum = Vix.Vips.Operation.add(im, [0, 128, 127])
```

wdyt?

**Comment by kipcole9** [comment]
@akash-akya I think there is great value in Vix keeping focused on the raw operations - it means it can be agile against `libvips` releases. And the depth of the functionality is already vast!   

It also turns out that on investigating more what `pyvips` is doing that the arithmetic operators aren't doing what I thought - they use `linear/3` when the argument is a `int` or `vector`:
```python
    # operator overloads

    def __add__(self, other):
        if isinstance(other, pyvips.Image):
            return self.add(other)
        else:
            return self.linear(1, other)

    def __radd__(self, other):
        return self.__add__(other)

    def __sub__(self, other):
        if isinstance(other, pyvips.Image):
            return self.subtract(other)
        else:
            return self.linear(1, _smap(lambda x: -1 * x, other))

    def __rsub__(self, other):
        return self.linear(-1, other)

    def __mul__(self, other):
        if isinstance(other, Image):
            return self.multiply(other)
        else:
            return self.linear(other, 0)

    def __rmul__(self, other):
        return self.__mul__(other)

    # a / const has always been a float in vips, so div and truediv are the
    # same
    def __div__(self, other):
        if isinstance(other, pyvips.Image):
            return self.divide(other)
        else:
            return self.linear(_smap(lambda x: 1.0 / x, other), 0)
```
I will follow this approach in the work I'm doing and when that's ready to share in a couple of weeks it might be clearer whether a higher level abstraction is best done in `Vix` or some other place.

I must say that despite the challenges I'm really enjoying being back in image processing. Photography is a passion but I've never dived into the math of how transforms work. And while `libvips` is an amazing piece of work, the lack of tutorial-level documentation makes for a serious challenge.  Perhaps that's something I can contribute back as well.

**Comment by kipcole9** [comment]
I've implemented most of the matrix math functions in a manner similar to the `pyvips` library and the examples (creating gradients) are working as expected. Closing the issue, sorry for the noise.

I'll have a simple set of functions of slightly higher level of abstraction for discussion early next week.

**Comment by akash-akya** [comment]
@kipcole9 happy to hear that you are finding it useful for Photography related use cases! I use mostly use it for my hobby project involving OCR.

Agree on documentation part -- It's not obvious how to achieve what I want using the vips functionality, even though all the tools are available. Thats where more tutorials and the high level abstractions might potentially help. 

I tried to document most common operations in the Livebooks, but there is room for improvement of course.

Btw, feel free to open the issue and share your thoughts, it might be useful for the others :)
