### ISSUE TITLE
Put error macro behind G_DEBUG?

### ISSUE THREAD

**Issue by kipcole9** [akash-akya/vix#38]
For `libvips`, setting the `G_DEBUG` environment variable influences debug output at runtime which is very helpful to reduce noise.  However `vix` has an `error` that cannot be silened. Why would we want to silence error output?  Not all errors compromise execution. For example.`vips_profile_load` loads an ICC profile. If the profile is not found an `{:error, term()}` tuple is returned in Elixir. But there is also output to the terminal from the `error` macro and that output isn't really helpful.

### Current situation

in `vix/c_src/utils.h`:
```c
#define error(...)                                                             \
  do {                                                                         \
    enif_fprintf(stderr, "%s:%d\t(fn: \"%s\")  - ", __FILE__, __LINE__,        \
                 __func__);                                                    \
    enif_fprintf(stderr, __VA_ARGS__);                                         \
    enif_fprintf(stderr, "\n");                                                \
  } while (0)

#define SET_RESULT_FROM_VIPS_ERROR(env, label, res)                            \
  do {                                                                         \
    res.is_success = false;                                                    \
    res.result = enif_make_tuple2(env, make_binary(env, label),                \
                                  make_binary(env, vips_error_buffer()));      \
    error("%s: %s", label, vips_error_buffer());                               \
    vips_error_clear();                                                        \
  } while (0)
```
We can see that `SET_RESULT_FROM_VIPS_ERROR` will always output  via `enif_fprintf`. 

### Desired outcome

`error` macro can be asked to not output errors. Either behind the `G_DEBUG` flag like `libvips` or some other mechanism.

**Comment by akash-akya** [comment]
Noted @kipcole9. I'll push changes to enable/disable error logs on the fly. And turn it off by default.

**Comment by akash-akya** [comment]
@kipcole9 I added support for configuring error logging using `VIX_LOG_ERROR` env variable, It's in master now. Supporting `G_DEBUG` is a bit more complex, so skipping it for now. 

Thanks for the issue and suggestions!

**Comment by kipcole9** [comment]
@akash-akya thank you, really appreciate your support. Vix is a great library and I'm aiming to get my first version of `Image` out soon.  It does depend on the `Access` implementation so I wonder if you would consider a `0.9.0` release with the accumulated changes soon?

No expectation at all that you put your messaged behind `G_DEBUG`, that's not an issue at all!

**Comment by akash-akya** [comment]
@kipcole9 yes! I will cut a new version by today. 
Excited to see first `Image` version 🎉

**Comment by akash-akya** [comment]
@kipcole9 `0.9.0` release is published

**Comment by kipcole9** [comment]
Thanks much @akash-akya, updated and all tests passing. Now working hard on documentation for `Image` to see if I can get it out the door this evening.

One question - very curious behaviour.  `Vix.Vips.Operation.thumbnail/2` produces different binary output on my Intel iMac Pro and my ARM MacBook Pro.  Both images render the same. The but binary compare (which I use in tests per your original examples) is quite different.

All other transform functions produce the same binary output (at least those I have tested).

Any Ideas?  Not a deal break, just curious!

**Comment by akash-akya** [comment]
What is the source image format? For JPEG format, that might happen if 2 machines are using different decoder libraries. Can you try with a format like `PNG` and see if you can reproduce the same issue?

Also, If possible, please share `vips --vips-config` from both machines
