### ISSUE TITLE
Operation.composite/3 doesn't call to_nif_term/2 for blend modes

### ISSUE THREAD

**Issue by kipcole9** [akash-akya/vix#42]
`Vix.Vips.Operation.composite/3` takes a list of blend modes as the second argument. However while the type is annotated as `[integer()]` (which is correct given it is declared as `int *mode` in `libvips`), this would normally be expected to be `[Vix.Vips.Enum.VipsBlendMode.t()]` to be consistent with other functions.

I appreciate that these functions are generated at compile time based upon introspecting `libvips`. Perhaps therefore there is no "fix" for this. But maybe a documentation entry (also difficult given I know the docs are auto generated) to note the need to call `Vix.Vips.Enun.VipsBlendMode.to_nif_term/2` would be helpful?

**Comment by akash-akya** [comment]
Yes, I'm aware of this. Types we get from libvips is flat (`VipsArrayInt`, `VipsArrayImage` etc) so this is something we have to do at our end. I think we can have some level of abstraction in place to support casting. I'll look into this. `to_nif_term` is meant to be for internal use, so I  want to avoid exposing those to the user.

Thanks again for the contribution!
