### ISSUE TITLE
Vix.Vips.Operation.getpoint/3 returns floats, even for UCHAR images

### ISSUE THREAD

**Issue by kipcole9** [akash-akya/vix#47]
### Issue 
`Vix.Vips.Operation.getpoint/3` returns float values even when the image format is `:VIPS_FORMAT_UCHAR`.

### Example
```elixir
# Shouldn't the return values be integers?
iex> Vix.Vips.Operation.getpoint i, 200, 200
{:ok, [21.0, 22.0, 27.0]}

iex> Vix.Vips.Image.interpretation i
:VIPS_INTERPRETATION_sRGB
iex> Vix.Vips.Image.format i        
:VIPS_FORMAT_UCHAR
```

**Comment by akash-akya** [comment]
`getpoint` always return [array of double](https://github.com/libvips/libvips/blob/f11b58ff6c602549d553c57e506142de5b6d28e9/libvips/arithmetic/getpoint.c#L74-L82) irrespective of format. libvips document it as such as well: https://www.libvips.org/API/current/libvips-arithmetic.html#vips-getpoint.

Side note, I think this function is not meant to be used for doing operation by reading pixels one after another. It seems to be too expensive.

**Comment by kipcole9** [comment]
Thanks @akash-akya for the clarification.

Most definitely not a good function for iterating over the array!!!  There was a question on slack about getting the color of a random pixel. And I think `getpoint/3` is probably ok for that.
