### ISSUE TITLE
implementation of new_from_image?

### ISSUE THREAD

**Issue by ringofhealth** [akash-akya/vix#5]
Hello again! 

I am trying to raise a PR to implement a method that allows image to be created in memory instead of just creating from file. Anaglous to the rubyVips 

basically like this
https://github.com/libvips/ruby-vips/blob/master/lib/vips/image.rb#L505

```

    def new_from_image value
      pixel = (Vips::Image.black(1, 1) + value).cast(format)
      image = pixel.embed 0, 0, width, height, extend: :copy
      image.copy interpretation: interpretation, xres: xres, yres: yres,
                 xoffset: xoffset, yoffset: yoffset
    end
```

basically allowing vix to dynamically generate a image in memory from text or color matrix and overlay it to create complex patterns 

like this
```
text = Vips::Image.text ARGV[2], width: 200, dpi: 200, font: "sans bold"
text = text.rotate(-45)
# make the text transparent
text = (text * 0.3).cast(:uchar)
text = text.gravity :centre, 200, 200
text = text.replicate 1 + im.width / text.width, 1 + im.height / text.height
text = text.crop 0, 0, im.width, im.height

# we make a constant colour image and attach the text mask as the alpha
overlay = (text.new_from_image [255, 128, 128]).copy interpretation: :srgb
overlay = overlay.bandjoin text`

```

However I am having a hard time getting my currunt implementation to accept an array of rgb values as an alpha layer, can you point me to the right direction?

Here is my implementation so far

```
  def new_from_image(band, width, height) when is_list(band) do
    bands = Enum.map(band, fn b -> {:band, b} end)

    with {:ok, i0} <- Operation.black(1, 1, bands),
         {:ok, i1} <- Operation.cast(i0, :VIPS_FORMAT_UCHAR),
         {:ok, i2} <- Operation.embed(i1, 0, 0, width, height, extend: :VIPS_EXTEND_COPY),
         {:ok, final} <- Operation.copy(i2) do
      {:ok, final}
    else
      {:error, e} = error ->
        error

      unknown_error ->
        {:error, unknown_error}
    end
```

vix is yelling at me because apparently when I try to compose, I dont have the same amount of bands

```
vix/c_src/vips_operation.c:225	(fn: "nif_vips_operation_call")  - failed to build operation, error: composite2: images do not have same numbers of bands

code/elixir/venus/deps/vix/c_src/utils.c:39	(fn: "vix_error")  - failed to build operation

```

What am I doing wrong here?

**Comment by akash-akya** [comment]
It should be something like

```elixir
  def new_from_image(value, width, height) when is_list(value) do
    bands = length(value)

    with {:ok, i0} <- Operation.black(1, 1, bands: bands),
         {:ok, i1} <- Operation.linear(i0, [1], value),
         {:ok, i2} <- Operation.cast(i1, :VIPS_FORMAT_UCHAR),
         {:ok, i3} <- Operation.embed(i2, 0, 0, width, height, extend: :VIPS_EXTEND_COPY),
         {:ok, final} <- Operation.copy(i3) do
      {:ok, final}
    else
      {:error, e} = error ->
        error

      unknown_error ->
        {:error, unknown_error}
    end
  end
```
where value is rgb value as list, 
```
new_from_image([150,200,150], 518, 389)
```

To replicate `new_from_image` function in ruby properly, we need `Image.format` and `Image.interpretation` functions. I'll look into adding it

**Comment by ringofhealth** [comment]
well since elixir isnt oop like ruby, it doesnt have to be exactly the same implementation right? as long as it does the same thing? why isnt the implementation you posted enough for this?

**Comment by akash-akya** [comment]
> it doesnt have to be exactly the same implementation right? as long as it does the same thing?

Yes, I was referring to interface though. For example currently for `Image.width/1` and `Image.height/1` one has to pattern match tuple before getting the value. `Operation.op(Image.width!(image), Image.height!(image))` might look simpler (or if we have an image struct then we can just do image.height and image.width)

> why isnt the implementation you posted enough for this?

Currently, it's using hard-coded format right? also, I would prefer to keep the behavior the same if we are going to port exiting function from ruby-vips so less surprise to the user.

It would be something like this I guess
```elixir
  def new_from_image!(image, value) is_list(value) do
    # TODO: Image.format(image)
    format = :VIPS_FORMAT_UCHAR

    pixel =
      Operation.black!(1, 1)
      |> Operation.linear!([1], value)
      |> Operation.cast!(format)

    {:ok, width} = Image.width(image)
    {:ok, height} = Image.height(image)
    new_image = Operation.embed!(pixel, 0, 0, width, height, extend: :VIPS_EXTEND_COPY)

    {:ok, xres} = Image.xres(image)
    {:ok, yres} = Image.yres(image)
    {:ok, xoffset} = Image.xoffset(image)
    {:ok, yoffset} = Image.yoffset(image)

    # TODO: Image.interpretation(image)
    interpretation = :VIPS_INTERPRETATION_sRGB

    Operation.copy!(new_image,
      interpretation: interpretation,
      xres: xres,
      yres: yres,
      xoffset: xoffset,
      yoffset: yoffset
    )
  end
```

**Comment by ringofhealth** [comment]
okay right! you are right, cause the ruby implementation has implicit access to to the image entity

**Comment by akash-akya** [comment]
Hi @ringofhealth, I added this function using the c version of it. Please check master if possible :)

I'll create a version after some time.
