### ISSUE TITLE
Exception raise when specifying suffix to Vix.Vips.Image.new_from_enum/2

### ISSUE THREAD

**Issue by kipcole9** [akash-akya/vix#50]
Image streaming working well. Tested with File.stream! and also ExAws.S3 with [minio](https://min.io).  However when specifying a suffix the following error occurs:
```elixir
iex(1)> stream = File.stream! "test/images/puppies.jpg", [], 2048      
%File.Stream{
  line_or_bytes: 2048,
  modes: [:raw, :read_ahead, :binary],
  path: "test/images/puppies.jpg",
  raw: true
}
iex(2)> Vix.Vips.Image.new_from_enum(stream, ".jpg")                   
{:error, "Failed to create image from VipsSource"}
** (EXIT from #PID<0.377.0>) shell process exited with reason: an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, "Broken pipe"}
        (vix 0.9.0) lib/vix/vips/image.ex:178: anonymous fn/2 in Vix.Vips.Image.new_from_enum/2
        (elixir 1.13.2) lib/enum.ex:942: anonymous fn/3 in Enum.each/2
        (elixir 1.13.2) lib/enum.ex:4144: anonymous fn/3 in Enum.each/2
        (elixir 1.13.2) lib/stream.ex:1559: Stream.do_element_resource/6
        (elixir 1.13.2) lib/enum.ex:4144: Enum.each/2
        (vix 0.9.0) lib/vix/vips/image.ex:177: anonymous fn/2 in Vix.Vips.Image.new_from_enum/2
```
This also results in an `iex` restart.

If specifying the suffix only as "jpg" the same error is returned but without an exception being raised:
```elixir
iex(1)> stream = File.stream! "test/images/puppies.jpg", [], 2048
%File.Stream{
  line_or_bytes: 2048,
  modes: [:raw, :read_ahead, :binary],
  path: "test/images/puppies.jpg",
  raw: true
}
iex(2)> Vix.Vips.Image.new_from_enum(stream, "jpg")              
{:error, "Failed to create image from VipsSource"}
```

**Comment by akash-akya** [comment]
This is mostly incorrect param name and documentation. The second parameter is not suffix, but loader options.

> Load options may be given in option_string as "[name=value,...]"

Loader options are similar to what we specify for `new_from_file` ex: `[shrink=2]` for `jpegload`

**Comment by kipcole9** [comment]
Ahhhh, ok, got it.  In face in `Image.open/2` I used a keyword list as options and then format them as loader options so I can reuse that for `new_from_enum/2`. I should have checked the `libvips` documentation, sorry for the noise.

**Comment by akash-akya** [comment]
> In face in Image.open/2 I used a keyword list as options and then format them as loader options so I can reuse that for new_from_enum/2

Nice! we should do something similar here as well.

Btw this is a valid issue which needs to be fixed. Thanks for raising it :)
