### ISSUE TITLE
Vix won't build on NixOS even with libvips properly installed

### ISSUE THREAD

**Issue by pmarreck** [akash-akya/vix#55]
full command output:

```
  yolo U:9  ~/Documents/mpnetwork                                                                                                   16:06:25  pmarreck
❯ NIX_DEBUG=1 mix test
==> vix
make[1]: Entering directory '/home/pmarreck/Documents/mpnetwork/deps/vix/c_src'
cc -O3 -std=c11 -finline-functions -Wall -Werror -Wmissing-prototypes -D_POSIX_C_SOURCE=200809L -fPIC -I /nix/store/9d5ni2fbn372zh93faz397283192cb09-erlang-24.2/lib/erlang/erts-12.2/include -I /nix/store/9d5ni2fbn372zh93faz397283192cb09-erlang-24.2/lib/erlang/usr/include `pkg-config vips --cflags`  -c -o /home/pmarreck/Documents/mpnetwork/deps/vix/c_src/vips_foreign.o /home/pmarreck/Documents/mpnetwork/deps/vix/c_src/vips_foreign.c
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
HARDENING: disabled flags: pie pic format stackprotector fortify strictoverflow
extra flags before to /nix/store/as1xzrm2921pnxx4jvxj39jn4v88wdy1-gcc-11.3.0/bin/gcc:
  ''
original flags to /nix/store/as1xzrm2921pnxx4jvxj39jn4v88wdy1-gcc-11.3.0/bin/gcc:
  -O3
  -std=c11
  -finline-functions
  -Wall
  -Werror
  -Wmissing-prototypes
  -D_POSIX_C_SOURCE=200809L
  -fPIC
  -I
  /nix/store/9d5ni2fbn372zh93faz397283192cb09-erlang-24.2/lib/erlang/erts-12.2/include
  -I
  /nix/store/9d5ni2fbn372zh93faz397283192cb09-erlang-24.2/lib/erlang/usr/include
  -c
  -o
  /home/pmarreck/Documents/mpnetwork/deps/vix/c_src/vips_foreign.o
  /home/pmarreck/Documents/mpnetwork/deps/vix/c_src/vips_foreign.c
extra flags after to /nix/store/as1xzrm2921pnxx4jvxj39jn4v88wdy1-gcc-11.3.0/bin/gcc:
  -B/nix/store/scd5n7xsn0hh0lvhhnycr9gx0h8xfzsl-glibc-2.34-210/lib/
  -idirafter
  /nix/store/dwsi3wsqpqm0hpzdm9fsxc7q732p9xwi-glibc-2.34-210-dev/include
  -idirafter
  /nix/store/as1xzrm2921pnxx4jvxj39jn4v88wdy1-gcc-11.3.0/lib/gcc/x86_64-unknown-linux-gnu/11.3.0/include-fixed
  -B/nix/store/j132k1ncfn6gjfd2f5s1gz37170rch4h-gcc-11.3.0-lib/lib
  -B/nix/store/ag2bpk0lzjvj409znklrz5krkpc5imzs-gcc-wrapper-11.3.0/bin/
/home/pmarreck/Documents/mpnetwork/deps/vix/c_src/vips_foreign.c:1:10: fatal error: glib-object.h: No such file or directory
    1 | #include <glib-object.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:58: /home/pmarreck/Documents/mpnetwork/deps/vix/c_src/vips_foreign.o] Error 1
make[1]: Leaving directory '/home/pmarreck/Documents/mpnetwork/deps/vix/c_src'
make: *** [Makefile:5: all] Error 2
could not compile dependency :vix, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile vix", update it with "mix deps.update vix" or clean it with "mix deps.clean vix"
==> mpnetwork
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. If you are using
Ubuntu or any other Debian-based system, install the packages
"build-essential". Also install "erlang-dev" package if not
included in your Erlang/OTP version. If you're on Fedora, run
"dnf group install 'Development Tools'".

  yolo U:9  ~/Documents/mpnetwork                                                                                                   16:08:38  pmarreck
 1 ❯ ff --help
Find File (pmarreck wrapper function)
Usage: ff [[<start path, defaults to .>] <searchterm>]
This function is defined in /home/pmarreck/.profile
(ff with no arguments lists all files recursively from $PWD)
  yolo U:9  ~/Documents/mpnetwork                                                                                                   11:16:17  pmarreck
❯ ff / "glib-object.h"
fd -HI glib-object.h /
/nix/store/va7sw50lfrpjriam6x9llbg47zn18n3v-glib-2.72.3-dev/include/glib-2.0/glib-object.h
/nix/store/mmwc0xqwxz2s4j35w7wd329hajzfy2f1-glib-2.72.3-dev/include/glib-2.0/glib-object.h
/nix/store/jxc7b1vvw2a58vv9pxdigiz9rm63jkxb-glib-2.72.3-dev/include/glib-2.0/glib-object.h
  yolo U:9  ~/Documents/mpnetwork                                                                                                   11:35:59  pmarreck
❯

```
my nixos configuration: https://github.com/pmarreck/nix_machine_configs/blob/yolo/system76_thelio_nixos/configuration.nix
(this file should theoretically enable you to erect NixOS in a VM with my exact machine configuration, you basically install NixOS in a VM, replace `/etc/nixos/configuration.nix` with my file, and then run something like `NIX_DEBUG=1 sudo nixos-rebuild switch` and wait)

The project I'm trying to build: https://github.com/pmarreck/mpnetwork (you can rename .env.for_testing to .env if it complains about missing env vars)

**Comment by pmarreck** [comment]
I believe it may be an easy fix; it can't find the header file, but (as you can see) it's there, it's just inside a glib-2.0 directory; normally, pkg-config handles this, but there's no .pc file anywhere to tell it how to handle this

**Comment by akash-akya** [comment]
Hi @pmarreck,

Just to double-check can you confirm you have `vips` installed? 
The header file error is because `pkg-config vips --cflags` is failing to find `vips.pc` as you pointed out. So even if you glib installed properly, we can still see this error if vips is not installed.

I tried to reproduce this using nixos in mac with minimal config and it seems to be working. Note that this is my first encounter with nixos, so please point out if I'm doing something wrong here.

```
$ cat configuration.nix
let
  unstable = import (fetchTarball https://nixos.org/channels/nixos-unstable/nixexprs.tar.xz) { };
in
{ nixpkgs ? import <nixpkgs> {} }:
with nixpkgs; mkShell {
  buildInputs = [ unstable.vips pkg-config git elixir ];
}%

$ nix-shell configuration.nix --pure

[nix-shell:~]$ pkg-config vips --libs
-L/nix/store/bsgl4qp61651l9q6g9k9ppzjl73ck21b-vips-8.12.2/lib -L/nix/store/w54l5s0cgbbf70s36jbx06yjp74am8c1-glib-2.72.3/lib -lvips -lgobject-2.0 -lglib-2.0

[nix-shell:~]$ pkg-config vips --cflags
-I/nix/store/2a214ggvd81h02m5n8l4l66llpx5sv94-vips-8.12.2-dev/include -I/nix/store/fq54f9l2f6xvrf9c8kfjyg61a8j5w6vz-glib-2.72.3-dev/include -I/nix/store/fq54f9l2f6xvrf9c8kfjyg61a8j5w6vz-glib-2.72.3-dev/include/glib-2.0 -I/nix/store/w54l5s0cgbbf70s36jbx06yjp74am8c1-glib-2.72.3/lib/glib-2.0/include

[nix-shell:~]$ cd repo/elixir/vix-temp/

[nix-shell:~/repo/elixir/vix-temp]$ mix compile
==> vix
make[1]: Entering directory '/Users/akash/repo/elixir/vix-temp/c_src'
clang -O3 -std=c11 -finline-functions -Wall -Werror -Wmissing-prototypes -D_POSIX_C_SOURCE=200809L -fPIC -I /nix/store/k6g13v9dzgwmhplyi0izjnaja8fhlnbc-erlang-24.2/lib/erlang/erts-12.2/include -I /nix/store/k6g13v9dzgwmhplyi0izjnaja8fhlnbc-erlang-24.2/lib/erlang/usr/include `pkg-config vips --cflags`  -c -o /Users/akash/repo/elixir/vix-temp/c_src/pipe.o /Users/akash/repo/elixir/vix-temp/c_src/pipe.c
clang -O3 -std=c11 -finline-functions -Wall -Werror -Wmissing-prototypes -D_POSIX_C_SOURCE=200809L -fPIC -I /nix/store/k6g13v9dzgwmhplyi0izjnaja8fhlnbc-erlang-24.2/lib/erlang/erts-12.2/include -I /nix/store/k6g13v9dzgwmhplyi0izjnaja8fhlnbc-erlang-24.2/lib/erlang/usr/include `pkg-config vips --cflags`  -c -o /Users/akash/repo/elixir/vix-temp/c_src/vix.o /Users/akash/repo/elixir/vix-temp/c_src/vix.c
clang -O3 -std=c11 -finline-functions -Wall -Werror -Wmissing-prototypes -D_POSIX_C_SOURCE=200809L -fPIC -I /nix/store/k6g13v9dzgwmhplyi0izjnaja8fhlnbc-erlang-24.2/lib/erlang/erts-12.2/include -I /nix/store/k6g13v9dzgwmhplyi0izjnaja8fhlnbc-erlang-24.2/lib/erlang/usr/include `pkg-config vips --cflags`  -c -o /Users/akash/repo/elixir/vix-temp/c_src/vips_image.o /Users/akash/repo/elixir/vix-temp/c_src/vips_image.c
clang -O3 -std=c11 -finline-functions -Wall -Werror -Wmissing-prototypes -D_POSIX_C_SOURCE=200809L -fPIC -I /nix/store/k6g13v9dzgwmhplyi0izjnaja8fhlnbc-erlang-24.2/lib/erlang/erts-12.2/include -I /nix/store/k6g13v9dzgwmhplyi0izjnaja8fhlnbc-erlang-24.2/lib/erlang/usr/include `pkg-config vips --cflags`  -c -o /Users/akash/repo/elixir/vix-temp/c_src/utils.o /Users/akash/repo/elixir/vix-temp/c_src/utils.c
clang -O3 -std=c11 -finline-functions -Wall -Werror -Wmissing-prototypes -D_POSIX_C_SOURCE=200809L -fPIC -I /nix/store/k6g13v9dzgwmhplyi0izjnaja8fhlnbc-erlang-24.2/lib/erlang/erts-12.2/include -I /nix/store/k6g13v9dzgwmhplyi0izjnaja8fhlnbc-erlang-24.2/lib/erlang/usr/include `pkg-config vips --cflags`  -c -o /Users/akash/repo/elixir/vix-temp/c_src/vips_interpolate.o /Users/akash/repo/elixir/vix-temp/c_src/vips_interpolate.c
....
```
Ultimately it failed with linker error after compilation, but that is a different issue I think.

Also can you share output for 
```
$ pkg-config vips --libs --cflags
$ pkg-config glib-2.0 --libs --cflags
```

**Comment by pmarreck** [comment]
```
❯ vips --version
vips-8.12.2-Thu Jan  1 00:00:01 UTC 1970
```

**Comment by pmarreck** [comment]
```
 127 ❯ pkg-config vips --libs --cflags
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
```
Well, that is odd. These commands were consecutive. vips is there but pkg-config can't "see" it?

**Comment by pmarreck** [comment]
```
❯ pkg-config glib-2.0 --libs --cflags
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
```
Strange. But so is Nix, in a way. Forces you to specify all dependencies and make no implicit assumptions. So if something is actually installed, but something that depends on it didn't declare it as a dependency, it literally won't see it.

**Comment by pmarreck** [comment]
looks like someone solved a similar issue here, but I'm still digesting it
https://discourse.nixos.org/t/how-to-add-pkg-config-file-to-a-nix-package/8264

**Comment by akash-akya** [comment]
FWIW, I faced exact error at first. It was because I hadn't installed `pkg-config` and when I run the command `pkg-config vips --libs --cflags` it was falling back host (macos) `pkg-config` binary and failing. It was fixed after I installed `pkg-config` and specified `--pure`.

**Comment by pmarreck** [comment]
@akash-akya As I want to eventually use a variant of the `configuration.nix` recipe to deploy my code, I'd like it to work declaratively- I've never used the `--pure` option but I suppose that's a commandline option to either one of the nix commands or pkg-config itself? How do you specify `--pure` in a configuration context? (actually, what was the command you used?)

**Comment by akash-akya** [comment]
Ok. I used `nix-shell` which I think is like a temporary shell to experiment without actually installing system-wide.

I already mentioned this in last [comment](https://github.com/akash-akya/vix/issues/55#issuecomment-1204352458):

Created `configuration.nix` file somewhere:
```
let
  unstable = import (fetchTarball https://nixos.org/channels/nixos-unstable/nixexprs.tar.xz) { };
in
{ nixpkgs ? import <nixpkgs> {} }:
with nixpkgs; mkShell {
  buildInputs = [ unstable.vips pkg-config git elixir ];
}
```

And opened nix-shell with this config, which installed all above-mentioned packages.
```
$ nix-shell configuration.nix --pure
```

I think you can double-check which pkg-config binary you are using (`which pkg-config`)

**Comment by pmarreck** [comment]
By the way, I'm still new to Nix/NixOS but speaking as another developer (who thinks many more developers would love this concept, even though it took me SO LONG to finally come around to it), I highly suggest you check it out. I got past most of the initial concepts (which were an intimidating amount of new language, such as "derivations") by just reading the whitepaper that started it all https://edolstra.github.io/pubs/nspfssd-lisa2004-final.pdf and although I cannot quite write my own derivations yet (other than really basic ones), I can pretty easily modify others I find (thanks to Google). A derivation is just a pure, anonymous function that takes arguments (codebase, any build "state", env vars, linker arguments etc.) and returns "values" (build outputs usually); it's really a nice system if you are already onboard the whole "functional" idea... It's just that, but as applied to creating a dependency graph (an "OS config"). Unlike, say, debugging Dockerfiles, when you have a working definition in a .nix file, there's a reasonably good chance that it will build *forever* (deterministically).

**Comment by pmarreck** [comment]
ah, just saw your response, stand by

**Comment by pmarreck** [comment]
ah I see, you basically instantiated a pure shell (free of any of my local env) with the necessary pieces, and it worked, which basically means that something is screwed up in my local environment, I think. This is actually a great debugging step I can take in the future, and nix makes it very easy, so thanks for this! I will try it now and investigate

**Comment by pmarreck** [comment]
```
❯ which pkg-config
/run/current-system/sw/bin/pkg-config
```
so I'm definitely using the nix-installed pkg-config. brb after instantiating a clean shell

**Comment by pmarreck** [comment]
OK so I got it to build and test successfully using this `shell.nix` environment setup: https://github.com/pmarreck/mpnetwork/blob/yolo/shell.nix and this modified host config (basically just added postgres service with a default admin user): https://github.com/pmarreck/nix_machine_configs/blob/yolo/system76_thelio_nixos/configuration.nix

So now that I have a known-good state I can walk it towards my default dev env and see what is misconfigured. (May update this with that info to help any future wanderers.)

Thanks!

**Comment by akash-akya** [comment]
I heard many good things about nix. And I'm wanting to try it out from a long time, but not able to find time to actually try it out :(. Thanks for sharing the overview and paper, I will check it out.

> OK so I got it to build and test successfully using this shell.nix environment setup: https://github.com/pmarreck/mpnetwork/blob/yolo/shell.nix and this modified host config (basically just added postgres service with a default admin user): https://github.com/pmarreck/nix_machine_configs/blob/yolo/system76_thelio_nixos/configuration.nix

Nice, good to know! Please do update when you find out the issue, the default env. It might be useful to me at least when I make the switch to NixOS.

**Comment by pmarreck** [comment]
I have a 1 year old so I know how valuable time is, lol. I'd say check out the whitepaper, that's worth your time, just 13 pages for the core idea(s). I'm going to revisit what's wrong with my dev env when I can, and update here

**Comment by akash-akya** [comment]
I see, that makes sense, basically when we build something we know exactly how it is built.
Thanks for sharing this information.

**Comment by pmarreck** [comment]
It broke at some point again:
```
[warning] The on_load function for module Elixir.Vix.Nif returned:
{:error,
 {:load_failed,
  'Failed to load NIF library /home/pmarreck/Documents/mpnetwork/_build/prod/lib/vix/priv/vix: \'/nix/store/lxpdbaazqd2s79jx6lngr8nak2rjdaq1-glibc-2.34-210/lib/libm.so.6: version `GLIBC_2.35\' not found (required by /nix/store/akgjvj0if1aq0qcb0x5n3bh84a9lw21d-vips-8.13.0/lib/libvips.so.42)\''}}
  ```
I've tried including the unstable version of glibc (and glibcLocales) as build inputs, which are both at 2.35, but that doesn't fix it :/

I'm not a C programmer, but why is glibc so brittle?
