### ISSUE TITLE
[Proposal] Make Vix.Tensor.image_type/1 public

### ISSUE THREAD

**Issue by kipcole9** [akash-akya/vix#62]
I'm adding some introspection functions to `Image` and I'm standardising on representing the format of an image as the `Nx` type.  Would you consider changing `Vix.Tensor.image_type` to be public rather than private?

**Comment by akash-akya** [comment]
@kipcole9  you meant [`Vix.Tensor.nx_type`](https://github.com/akash-akya/vix/blob/master/lib/vix/tensor.ex#L28) right?
I see no reason to _not_ do that. We can make it public.
