### ISSUE TITLE
[Question] Operation.text/4 watermarking DPI sizing 

### ISSUE THREAD

**Issue by ringofhealth** [akash-akya/vix#78]
Hi again =) 

This might be a long shot, you actually helped me come up with this flow to watermark images. I am having some problem with the DPI config for watermark

```
 with {:ok, vipsimg} <- Image.new_from_file(input),
         max_width when not is_nil(max_width) <- Image.width(vipsimg),
         max_height when not is_nil(max_height) <- Image.height(vipsimg),
         {:ok, {original_text, _}} <-
           Operation.text("www.mywebsite.com/user/" <> user,
             dpi: round(max_width / 6),
             font: "Helvetica"
           ),
         {:ok, text} <- Operation.cast(original_text, :VIPS_FORMAT_UCHAR),
         {:ok, o0} <- new_from_image([255.0, 255.0, 255.0], max_width, max_height),
         {:ok, o2} <- Operation.copy(o0, interpretation: :VIPS_INTERPRETATION_sRGB),
         {:ok, o3} <- Operation.bandjoin([o2, text]),
         {:ok, overlay} <-
           Operation.composite2(
             vipsimg,
             o3,
             :VIPS_BLEND_MODE_OVER,
             x: 80,
             y: 80
           ),
         {:ok, final} <- Operation.thumbnail_image(overlay, size),
         :ok <- Vix.Vips.Image.write_to_file(final, output <> "[#{quality},strip]") do
      {:ok, output}
```

This takes an existing image, and put a watermark of mywebsite/user/username on the top left corner of the image. 

The problem I am having is that the text overlay is different in size. it definitely has something to do with this

`  dpi: round(max_width / 6) `

My guess is that with larger image, the DPI becomes larger. so the font actually becomes smaller the larger the image is, and vice versa

I want to keep my watermark text size proportional to the image, regardless of the image size. How would I go about and do the clculation for the DPI component for

```
Operation.text("www.mywebsite.com/user/" <> user,
             dpi: round(max_width / 6),
             font: "Helvetica"
           ),
```

Thank you for your help if you have an ideas!

**Comment by akash-akya** [comment]
Hi @ringofhealth, sorry for very late response, I had forgotten about this issue after seeing.

For the issue, I suggest not rely on the DPI and instead just scale the text to desired size.

For example, one way of doing that is

```elixir
{:ok, img} = Image.new_from_file(input)

max_height = 10_000

# change as required
scale = 0.5   # text width is half of input image width

{:ok, {text, _}} =
  Operation.text("www.mywebsite.com/user/foo",
    width: round(Image.width(img) * scale),
    rgba: true,
    height: max_height,  # have large max height to let libvips auto set it
    spacing: max_height  # to avoid line splitting
  )

{:ok, overlay} = Operation.composite2(img, text, :VIPS_BLEND_MODE_OVER, x: 80, y: 80)
```

Let me know if this helps are not, I can suggest alternative if not.

**Comment by ringofhealth** [comment]
this works! tyty! for this implementation

how does one adjust the the color of the text?

also whats interesting is that the text here might be variable in length.  I think the x, y coord of the composite2 is the 0,0 pos of the text layer. is there a way to always put to text in the absolute middle of the X plane?

**Comment by ringofhealth** [comment]
this is amazing! ty so much!!
