### ISSUE TITLE
Images without metadata crashes in Livebook

### ISSUE THREAD

**Issue by kwando** [akash-akya/vix#84]
Render of images without metadata fails to render in Livebook :)

<img width="919" alt="Skärmavbild 2022-12-18 kl  13 22 51" src="https://user-images.githubusercontent.com/891566/208298150-08fbcace-4bdc-4840-8ffa-0358d9567c4a.png">

**Comment by akash-akya** [comment]
This specific issue should be fixed with [removal of `orientation` metadata](https://github.com/akash-akya/vix/pull/85), I think. I'll check if this happens for other metadata.

Thanks for reporting the issue.

**Comment by RyoWakabayashi** [comment]
I have a similar problem.

<img width="926" alt="スクリーンショット 2023-01-31 15 24 25" src="https://user-images.githubusercontent.com/14919320/215683361-d75f0383-c800-4b99-860b-0f570e3b1acd.png">

**Comment by akash-akya** [comment]
@RyoWakabayashi thanks for reporting it. I'll push a fix soon
