### ISSUE TITLE
Support all vips targets for precompiled binaries

### ISSUE THREAD

**Issue by andryuha-salo** [akash-akya/vix#90]
By default `cc_precompiler` looks for a [set](https://github.com/cocoa-xu/cc_precompiler#linux) of popular targets, missing out on linuxmusl, for example. If I'm not mistaken, should be fixed by providing `:compilers` under `cc_precompiler` option in mix config

**Comment by akash-akya** [comment]
Yes cc_precompiler does support more targets but vix is also shipping libvips binaries along with the NIF which is managed separately. So the precompiler setup is bit more complicated. Also I don't have a machine to properly test these different targets.

I am mostly waiting to make the popular targets stable and gradually add support for all remaining platforms as required by the community. Which targets are you interested in?

**Comment by andryuha-salo** [comment]
I'm interested in `x86_64-linux-musl`, https://github.com/bitwalker/alpine-elixir has this arch

**Comment by akash-akya** [comment]
Ack. I'll try to add support for x86_64 & aarch64 musl soon.

**Comment by akash-akya** [comment]
@tosie @alappe @andryuha-salo pre-compiled binaries for musl based targets are ready for testing. Can anyone you please help to check for both `aarch64` and `x86_64` architecture?

You test your application by using vix with this commit in mix.exs

```elixir
{:vix, github: "akash-akya/vix", ref: "24f59e8"}
```

If you don't have any application to test, you can pull this branch and run test suite.
```
git clone --depth 1 https://github.com/akash-akya/vix.git --branch dev --single-branch
cd vix
mix deps.get
mix test
```

I will merge changes and cut release once someone confirms. Thanks!

**Comment by alappe** [comment]
```
==> vix
Downloading precompiled NIF to /root/.cache/vix-nif-2.16-x86_64-linux-musl-0.16.1-rc1.tar.gz
Compiling 27 files (.ex)
Generated vix app
.......................................................
(process:63): VIPS-WARNING **: 19:00:19.571: read gave 32 warnings

(process:63): VIPS-WARNING **: 19:00:19.571: VipsJpeg: Premature end of JPEG file
VipsJpeg: JPEG datastream contains no image

...........
19:00:19.714 [warning] argument must be stream of iodata
.....
Finished in 0.3 seconds (0.3s async, 0.00s sync)
71 tests, 0 failures
```

**Comment by akash-akya** [comment]
Test aarch64 musl target on raspberry-pi I had. 

Released `0.16.1` which support musl targets 🎉

**Comment by alappe** [comment]
Thank you very much!

**Comment by tosie** [comment]
Thanks very much! I couldn't find spare time to test things earlier ... Thanks again and have a great week.
