### ISSUE TITLE
Pre-built nif for x86_64-linux-musl possible?

### ISSUE THREAD

**Issue by alappe** [akash-akya/vix#91]
Thanks for this library!

Since I'm using alpine images, I would need to add build tools to the chain or introduce another build image into the docker process, so I wondered if it would be possible to provide a pre-built `x86_64-linux-musl` nif for every release too, without too much more effort on your end?

Best regards
Andreas

**Comment by akash-akya** [comment]
Hi @alappe Yes it can be done, I am looking into this and will release a version soon with the support.
Same as #90

**Comment by alappe** [comment]
Ah, I didn't see this one – sorry and thank you very much!
