### ISSUE TITLE
Unable to use Vix.Vips.Operation.pdfload/2 method in 0.16 version

### ISSUE THREAD

**Issue by aakashjhawar** [akash-akya/vix#92]
The newer 0.16 version of vix brings pre-compiled binaries but does not support [Vix.Vips.Operation.pdfload/2](https://hexdocs.pm/vix/0.15.1/Vix.Vips.Operation.html#pdfload/2) and [Vix.Vips.Operation.pdfload_buffer/2](https://hexdocs.pm/vix/0.15.1/Vix.Vips.Operation.html#pdfload_buffer/2) methods.

How do you recommend if we want to use these methods in the 0.16 version?

Also, if we use 0.15.1v of vix, we are facing the error which is already reported in this [issue](https://github.com/akash-akya/vix/issues/77).

**Comment by akash-akya** [comment]
Yes, the precompiled libvips only comes with most common formats targeting most common usecase. 

> How do you recommend if we want to use these methods in the 0.16 version?

You can skip using precompiled libvips and bring your own libvips library with support for formats you want by installing it manually using package manager. This was the default behavior before v0.16.0. To get this behavior in the newer versions set env `PLATFORM_PROVIDED_LIBVIPS=true`. More details here -- https://github.com/akash-akya/vix#pre-compiled-nif-and-libvips. Let me know if you face any issue with this.

> Also, if we use 0.15.1v of vix, we are facing the error which is already reported in this https://github.com/akash-akya/vix/issues/77

Did you try the solution mentioned in that issue thread? https://github.com/libvips/php-vips/issues/142#issuecomment-1188960441

**Comment by aakashjhawar** [comment]
Hi @akash-akya, I tried installing libvips by following the steps mentioned here https://github.com/libvips/php-vips/issues/142#issuecomment-1188960441 and I'm using 0.15.1 version of vix. 

However, I'm getting this error when I try load PDF. `UndefinedFunctionError) function Vix.Vips.Operation.pdfload/2 is undefined or private.`

Do you have any example of a Dockerfile where libvips is installed and you are able to use the Vips.Operation.pdfload/2 method?

**Comment by akash-akya** [comment]
You have to extra dependencies for PDF format support. Just installing `libpoppler-glib-dev` package should do it.
something like

```dockerfile
RUN \
  apt-get update && \
  apt-get install -y \
    git \
    glib-2.0-dev \
    libexif-dev \
    libexpat-dev \
    libffi-dev \
    libjpeg-dev \
    libpoppler-glib-dev \ # install dependency
    liblcms2-dev \
    libpng-dev \
    libtiff-dev \
    meson \
    unzip \
    wget
```


Can you share the Dockerfile you used?
You can read more details about the different format support and dependecnies needed to support different formats here -- https://github.com/libvips/libvips#pdfium
