### ISSUE TITLE
Error happened while installing vix from precompiled binary: missing checksum.exs

### ISSUE THREAD

**Issue by kianmeng** [akash-akya/vix#94]
```sh
$ mix deps.get
$ mix test
...
==> vix                                                                                                 
Downloading precompiled NIF to /home/foobar/.cache/vix-nif-2.16-x86_64-linux-gnu-0.16.1.tar.gz             
Error happened while installing vix from precompiled binary: missing checksum.exs file.                 

Attempting to compile vix from source...                                                                
make[1]: Entering directory '/home/foobar/src/contrib/elixir/vix/c_src'
```

```sh
$ rg checksum.exs
mix.exs
107:        ~w(lib checksum.exs mix.exs README.md LICENSE Makefile c_src/Makefile c_src/*.{h,c} c_src/g_object/*.{h,c}),
```

The `checksum.exs` file supposed to be part of the distribution but missing?

**Comment by akash-akya** [comment]
How are you fetching the app repo? are you using hex.pm or fetching directly from github. 

So precompiled binary is only available and meant to be used with hex.pm. I am open to change this behavior if required.

`elixir_make` also suggest the similar approach -- https://hexdocs.pm/elixir_make/precompilation_guide.html#generate-checksum-file

**Comment by kianmeng** [comment]
Fetch directly from GitHub.

If I understand correctly, we need to run this command first:

```sh
MIX_ENV=dev mix elixir_make.checksum --all --ignore-unavailable
```

to generate the `checksum.exs` file, thus resolve the error above?

**Comment by akash-akya** [comment]
If you want to test with pre-built binary then yes. `mix elixir_make.checksum --all` should create checksum.exs file.
Otherwise it will just try to compile NIF like before.

**Comment by kianmeng** [comment]
Do you want to me add this step to README? If not, I'll close this issue.

**Comment by akash-akya** [comment]
Yes please! that might help the user. Thanks
